# Generated by Django 5.0.4 on 2024-04-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_comment_email_comment_name_reply_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlpost',
            name='webPage',
            field=models.URLField(verbose_name=''),
        ),
    ]
