# Generated by Django 5.0.4 on 2024-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_comment_likes_reply_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
