# Generated by Django 5.0.4 on 2024-04-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_comment_likes_remove_reply_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='upvote',
        ),
        migrations.AlterField(
            model_name='urlpost',
            name='webPage',
            field=models.URLField(null=True, verbose_name=''),
        ),
    ]
